// const mouduleData = require("./math");
// const {add, sub} = require("./math");
// import multiply from "./math.js";
import mul from "./math.js";
import {add, sub} from "./math.js";
// console.log(add(1,2));
// console.log(sub(1,2));
// console.log(mouduleData);
// console.log(mul(2,3));
import randomColor from "randomcolor";
const color = randomColor();
console.log(color);